# Generated by Django 2.2.5 on 2019-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_contractor_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('location', models.TextField()),
                ('work_phone', models.IntegerField()),
                ('mobile_phone', models.IntegerField()),
                ('emergency_phone', models.IntegerField()),
                ('emergency_contact', models.IntegerField()),
                ('emergency_contact_note', models.TextField()),
                ('fax_number', models.IntegerField()),
                ('addressline_1', models.CharField(max_length=100)),
                ('addressline_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('province_state', models.CharField(max_length=25)),
                ('postal_code', models.IntegerField()),
                ('country_region', models.CharField(max_length=25)),
                ('website', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
