# Generated by Django 2.2.5 on 2019-09-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190923_0307'),
        ('orders', '0004_auto_20190925_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='assset_tracker_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('location_being_moved_to', models.TextField()),
                ('move_date', models.DateField()),
                ('due_for_pickup', models.DateField()),
                ('item_status', models.CharField(max_length=100)),
                ('detailed_note', models.TextField()),
                ('returned', models.BooleanField(default=False)),
                ('asset_tracking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
