# Generated by Django 2.2.3 on 2019-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190926_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='assset_tracker_activity',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
