# Generated by Django 2.2.3 on 2019-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_assset_tracker_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assset_tracker_activity',
            name='detailed_note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assset_tracker_activity',
            name='due_for_pickup',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assset_tracker_activity',
            name='item_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assset_tracker_activity',
            name='location_being_moved_to',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assset_tracker_activity',
            name='move_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assset_tracker_activity',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
