# Generated by Django 2.2 on 2019-09-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190926_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
