# Generated by Django 2.2 on 2019-09-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_tracking_id'),
        ('orders', '0011_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assset_tracker_activity',
            name='asset_tracking_id',
        ),
        migrations.AddField(
            model_name='assset_tracker_activity',
            name='asset_tracking_id',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
