# Generated by Django 2.2.3 on 2019-09-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_tracking_id'),
        ('orders', '0012_auto_20190927_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assset_tracker_activity',
            options={'verbose_name_plural': 'assset_tracker_activity'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Location'},
        ),
        migrations.AlterModelOptions(
            name='staff_contractor_company',
            options={'verbose_name_plural': 'staff_contractor_company'},
        ),
        migrations.RemoveField(
            model_name='assset_tracker_activity',
            name='asset_tracking_id',
        ),
        migrations.AddField(
            model_name='assset_tracker_activity',
            name='asset_tracking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
