# Generated by Django 2.2 on 2019-10-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20191003_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assset_tracker_activity',
            old_name='user',
            new_name='staff_name',
        ),
    ]
