# Generated by Django 2.2 on 2019-10-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20191003_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assset_tracker_activity',
            name='location_being_moved_to',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assset_tracker_activity',
            name='move_date',
            field=models.DateField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
