# Generated by Django 2.1.13 on 2019-10-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20191003_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_contractor_company',
            name='postal_code',
            field=models.CharField(max_length=25),
        ),
    ]
