# Generated by Django 2.2.5 on 2019-09-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
