# Generated by Django 2.2 on 2019-09-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracking_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
