# Generated by Django 2.2 on 2019-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_remove',
            field=models.DateTimeField(blank=True),
        ),
    ]
