# Generated by Django 2.2.3 on 2019-09-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20190923_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='privacy_policy_and_terms_of_service',
        ),
        migrations.DeleteModel(
            name='temppic',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='cover_check',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='paypal_url',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='profile_check',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='slug',
        ),
        migrations.AlterField(
            model_name='infor',
            name='passwordkey',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='userpreferance',
        ),
    ]
