# Generated by Django 2.2.3 on 2019-09-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190927_0151'),
        ('login', '0018_auto_20190925_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200, null=True)),
                ('phone_password', models.CharField(max_length=10, null=True)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('work_phone', models.IntegerField(default=0, null=True)),
                ('home_phone', models.IntegerField(default=0, null=True)),
                ('mobile_phone', models.IntegerField(default=0, null=True)),
                ('fax_number', models.IntegerField(default=0, null=True)),
                ('address_line_1', models.CharField(max_length=100, null=True)),
                ('address_line_2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('province_state', models.CharField(max_length=30, null=True)),
                ('postal_code_ZIP', models.CharField(max_length=20, null=True)),
                ('country_region', models.CharField(max_length=30, null=True)),
                ('web_page', models.URLField(null=True)),
                ('notes', models.TextField(max_length=1000, null=True)),
                ('archive', models.BooleanField(default=False, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('staff_contractor_company_id', models.ManyToManyField(null=True, to='orders.staff_contractor_company')),
            ],
        ),
    ]
