# Generated by Django 2.2.3 on 2019-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_staff_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_contractor',
            name='staff_contractor_company_id',
            field=models.ManyToManyField(to='orders.staff_contractor_company'),
        ),
    ]
