# Generated by Django 2.2.3 on 2019-09-27 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20190927_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_contractor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
