# Generated by Django 2.2 on 2019-09-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20190927_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_contractor',
            name='address_line_1',
            field=models.CharField(blank=True, default='trash', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='address_line_2',
            field=models.CharField(blank=True, default='trash', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='archive',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='country_region',
            field=models.CharField(blank=True, default='trash', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='fax_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='home_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='mobile_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='notes',
            field=models.TextField(blank=True, default='trash', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='phone_password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='postal_code_ZIP',
            field=models.CharField(blank=True, default='trash', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='province_state',
            field=models.CharField(blank=True, default='trash', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='staff_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='web_page',
            field=models.URLField(blank=True, default='trash'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='work_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
