# Generated by Django 2.1.13 on 2019-10-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20190927_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_contractor',
            name='fax_number',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='home_phone',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='mobile_phone',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='phone_password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='staff_contractor',
            name='work_phone',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
